# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - '**/l10n/*.dart'
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    sort_pub_dependencies: false
    require_trailing_commas: false
