name: mobile_portal_ui
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Riverpod
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  pedantic_mono: any

flutter:
  uses-material-design: true
